### PR TITLE
✨ Enable support for pydantic v2

### PR DESCRIPTION
**Pull request by azogue**
with new companion library `pydantic-settings`, where the `BaseSettings` is migrated.

**more info and context:** 
* FastAPI with Pydantic v2: https://github.com/tiangolo/fastapi/discussions/9709
* Migration Guide for Pydantic V2: https://docs.pydantic.dev/dev-v2/migration/

Hi @sabuhish, I've been testing the new versions on a _private_ development I'm working on (which is a fastapi server with zeroconf and MQTT connections), and having this library as a dependency, this was the only thing I had to change to make it work with it 🍀

Installing the pre-release versions with `pip install --pre --upgrade fastapi pydantic pydantic-settings` gets you these versions to test them 👌

When forking the repo, I saw that there were no tests for the fastapi integration, so I did them 😜 (in another PR: #63 )

### CODE REVIEW

**Comment by sabuhish** [comment]
Hi @azogue thanks for your PR on tests, I was amazed by that! That was great work, thanks for your efforts!

For this PR, do you think we should update pydantic version?

**Comment by azogue** [comment]
Hi @sabuhish, 

> For this PR, do you think we should update pydantic version?

After doing this one, I figured **this wasn't enough**, as the pinned version in pyproject.toml is limiting the update. I have a commit [in one of my branches in the fork](https://github.com/azogue/fastapi-mqtt/pull/1) changing this, I'll try to pick some changes to this PR to remove the pydantic<2 constrain here.

I think the repo should be able to work with both versions of pydantic, like it does not require a recent version of fastapi, because the jump to v2 is not going to be smooth (there are too many changes!). 

And the problem is that `BaseSettings` require a [different repo](https://github.com/pydantic/pydantic-settings) with pydantic v2 (is not included anymore). 

Right now I don't know how to express that in the pyproject (a dependency needed only if another dependency has version > 2), but I can give it a try 🤞

**Comment by azogue** [comment]
> Right now I don't know how to express that in the pyproject (a dependency needed only if another dependency has version > 2), but I can give it a try 🤞

The solution I found (and hope will work) is this:

```toml
[tool.poetry.dependencies]
fastapi = ">=0.80"
pydantic = ">=1.9.0"
# ...
[tool.poetry.dev-dependencies]
pydantic-settings = ">=2.0.0"
# ...
```

For any user installing or upgrading `fastapi-mqtt` on their own library/app/whatever, they could:
- be using a lower (but recent) version of fastapi + pydantic 1.9, and this one will continue working as before 👍
- be brave and use pydantic-v2 + super-recent fastapi, and this will also work, _only if `pydantic-settings` is also installed, which I think will be the usual, but, if not, it will just raise an `ImportError` trying to `from pydantic import BaseSettings`, easily fixable within a ~1min google search 😜)

> For this PR, do you think we should update pydantic version?

For this repo's dev environment, the poetry.lock file is updated, so we are already using it 🚀

The key is to not _require_ it. At some point in the future, we can raise the minimal version for fastapi + pydantic and include pedantic-settings in the main section 👌

**Comment by tim-timman** [comment]
Fixes https://github.com/sabuhish/fastapi-mqtt/issues/68. Bump.

**Comment by sabuhish** [comment]
This PR will be closed in favor of #69 and #70.

**Pull request closed without merging**
